services:
  gss_bot:
    build: ./src
    restart: always
    network_mode: host

    command: /entrypoint.sh
    mem_limit: 768m
    memswap_limit: 1024m
    volumes:
      - ./src/:/src/
      - ./ssl/:/ssl/:ro
      - ./imgs/:/imgs/
      - ./logs/:/gss_logs/
    env_file:
      - .env