services:
  gss_bot:
    build: ./src
    restart: always
    network_mode: host

    command: python /src/run.py
    volumes:
      - ./src/:/src/
      - ./ssl/:/ssl/
      - ./logs/:/gss_logs/
    env_file:
      - .env
