name: Deploy Pipeline

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2


      - name: Check for Docker-related changes
        id: check-changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            docker:
              - '**/Dockerfile'
              - '**/docker-compose.yml'
              - '**/requirements.txt'


      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /opt/mapp
            git pull origin main

            if [ "${{ steps.check-changes.outputs.docker }}" = "true" ]; then
              echo "Building Docker images..."
              docker compose build
            fi

            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f
